Models/Entities/Chapter.cs
namespace WebApplication1.Models.Entities
{
    public class Chapter
    {
        public int ID { get; set; }
        public int Order { get; set; }
        public string Title { get; set; }
        public string Content { get; set; } 
        public int BookID { get; set; }        
        public virtual Book Book { get; set; }
        public virtual ICollection<Comment> Comments { get; set;} = new List<Comment>();
        public virtual ICollection<User> Users { get; set; } = new List<User>();

    }
}

Controllers/BookController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using WebApplication1.Models.Entities;
using WebApplication1.Models.Repositories;

namespace WebApplication1.Controllers
{
    [Authorize]
    public class BookController : Controller
    {
        private IBookRepository _bookRepository;
        private UserManager<User> _userManager;
        private IUserReviewRepository _userReviewRepository;
        private IReviewRepository _reviewRepository;
        private IChapterRepository _chapterRepository;
        private IUserRepository _userRepository;

        public BookController(IBookRepository bookRepository, IUserReviewRepository userReviewRepository, UserManager<User> userManager, IReviewRepository reviewRepository, IChapterRepository chapterRepository, IUserRepository userRepository)
        {
            _bookRepository = bookRepository;
            _userReviewRepository = userReviewRepository;
            _userManager = userManager;
            _reviewRepository = reviewRepository;
            _chapterRepository = chapterRepository;
            _userRepository = userRepository;
        }

        [HttpGet]
        public async Task<IActionResult> Index(int Id)
        {
            await _bookRepository.CalculateRating(Id);
            Book book = await _bookRepository.GetById(Id);
            ViewBag.chaptersCount = _chapterRepository.GetAll(Id).Result.Count();
            int reviews = await _bookRepository.GetReviewsCount(Id);
            ViewBag.reviews = reviews;
            return View(book);
        }

        [HttpPost]
        public async Task<IActionResult> Bookmark(int Id)
        {
            if (User.Identity != null && User.Identity.IsAuthenticated)
            {
                User user = await _userManager.GetUserAsync(User);
                if (user != null)
                {
                    await _userRepository.BookmarkBook(user.Id, Id);
                    return Json(new { success = true });
                }
            }
            return RedirectToAction("Login","Account");
        }

        [HttpPost]
        public async Task<IActionResult> UnBookmark(int Id)
        {
            if (User.Identity != null && User.Identity.IsAuthenticated)
            {
                User user = await _userManager.GetUserAsync(User);
                if (user != null)
                {
                    await _userRepository.UnBookmarkBook(user.Id, Id);
                    return Json(new { success = true });
                }
            }
            throw new ArgumentNullException(nameof(User));
        }

    }
}

Controllers/ChapterController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.Design;
using System.Data;
using WebApplication1.Models.Entities;
using WebApplication1.Models.Repositories;

namespace WebApplication1.Controllers
{
    public class ChapterController : Controller
    {
        private IChapterRepository _chapterRepository;
        private IBookRepository _bookRepository;
        private ICommentRepository _commentRepository;
        private IUserCommentRepository _userCommentRepository;
        private UserManager<User> _userManager;
        public ChapterController(IChapterRepository chapterRepository, UserManager<User> userManager, IBookRepository bookRepository, ICommentRepository commentRepository, IUserCommentRepository userCommentRepository)
        {
            _chapterRepository = chapterRepository;
            _userManager = userManager;
            _bookRepository = bookRepository;
            _commentRepository = commentRepository;
            _userCommentRepository = userCommentRepository;
		}

		[Authorize(Roles = "PremiumUser, Admin")]
		public async Task<IActionResult> Index(int id)
        {
            if (User != null)
            {
                User user = await _userManager.GetUserAsync(User);
                if (user != null)
                {
                    Chapter chapter = await _chapterRepository.GetById(id);

                    List<Chapter> chapters = await _chapterRepository.GetAll(chapter.BookID);

                    Chapter next = chapters.Where(c => c.Order == chapter.Order + 1).FirstOrDefault();
                    Chapter prev = chapters.Where(c => c.Order == chapter.Order - 1).FirstOrDefault();
                    ViewBag.Next = next != null ? next.ID : 0;
                    ViewBag.Prev = prev != null ? prev.ID : 0;

                    Book book = await _bookRepository.GetById(chapter.BookID);
                    ViewBag.BookTitle = book.Name;
                    ViewBag.BookId = book.ID;

                    return View(chapter);
                }
            }

            return RedirectToAction("Login", "Account");
        }

		[Authorize]
		[HttpGet]
        public async Task<IActionResult> Chapters(int Id)
        {
            List<Chapter> chapters = await _chapterRepository.GetAll(Id);
            return View(chapters);
        }

		[Authorize(Roles = "Admin")]
		[HttpGet]
        public IActionResult Chapter()
        {
            return View(new Chapter());
        }

		[Authorize(Roles = "Admin")]
		[HttpPost]
        public async Task<IActionResult> Chapter(Chapter chapter)
        {
            if (chapter == null)
            {
                throw new ArgumentNullException(nameof(chapter));
            }
            await _chapterRepository.AddChapter(chapter);
            return Json(new { success = true });
        }

		[Authorize(Roles = "Admin")]
		[HttpGet]
        public async Task<IActionResult> Edit(int Id)
        {
            Chapter chapter = await _chapterRepository.GetById(Id);
            return View(chapter);
        }

		[Authorize(Roles = "Admin")]
		[HttpPost]
        public async Task<IActionResult> Edit(int Id, Chapter chapter)
        {
            if (chapter == null)
            {
                throw new ArgumentNullException(nameof(chapter));
            }
            await _chapterRepository.EditChapter(Id, chapter);
            return Json(new { success = true });
        }

		[Authorize(Roles = "Admin")]
		[HttpPost]
        public async Task<IActionResult> Delete(int Id)
        {
            await _chapterRepository.Delete(Id);
            return Json(new { success = true });
        }

		[Authorize(Roles = "Admin")]
		[HttpPost]
        public async Task<IActionResult> Up(int Id)
        {
            await _chapterRepository.Up(Id);
            return Json(new { success = true });
        }

		[Authorize(Roles = "Admin")]
		[HttpPost]
        public async Task<IActionResult> Down(int Id)
        {
            await _chapterRepository.Down(Id);
            return Json(new { success = true });
        }

    }
}

Views/Chapter/Chapter.cshtml
@model Chapter
@{
    Layout = null;
}


@using (Html.BeginForm())
{
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group row g-0 mb-3">
            @Html.LabelFor(m => m.Title, "Title", new { @class = "form-label" })
            <div class="col-md-8 offset-2">
                @Html.EditorFor(m => m.Title, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group row g-0 mb-3">
            @Html.LabelFor(m => m.Content, "Content", new { @class = "form-label" })
            <div class="col-md-8 offset-2">
                @Html.TextAreaFor(m => m.Content, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
            </div>
        </div>   
    </div>
}

Views/Chapter/Chapters.cshtml
@using Microsoft.AspNetCore.Identity;
@using WebApplication1.Models.Repositories;
@model List<Chapter>
@inject IUserRepository userRepository
@inject UserManager<User> userManager

@{
    Layout = null;
}

<div class="h1 text-center mb-4"><span id="chaptersCount" data="@Model.Count()"></span></div>

@foreach (Chapter chapter in Model)
{
    <div class="d-inline-block mb-2">
        @{
            string Title = "Chapter " + chapter.Order + " : " + chapter.Title;
            User user = await userManager.GetUserAsync(User);
            bool isRead = false;
            if (user != null)
            {
                isRead = await userRepository.IsReadChapter(user.Id, chapter.ID);
            }
            if (User.IsInRole("PremiumUser") || User.IsInRole("Admin"))
            {
                if (isRead == false)
                {
                    <span class="h5">
                        <a class="text-decoration-none text-xxl-center bg-dark bg-opacity-75 badge" asp-action="Index" asp-controller="Chapter" asp-route-id="@chapter.ID">@Title</a>
                    </span>
                }
                else
                {
                    <span class="h5">
                        <a class="text-decoration-none text-xxl-center bg-secondary badge" asp-action="Index" asp-controller="Chapter" asp-route-id="@chapter.ID">@Title</a>
                    </span>
                }
            }
            else
            {
                if (isRead == false)
                {
                    <span class="h5">
                        <a class="text-decoration-none text-xxl-center bg-dark bg-opacity-75 badge" asp-action="Payment" asp-controller="Payment">@Title</a>
                    </span>
                }
                else
                {
                    <span class="h5">
                        <a class="text-decoration-none text-xxl-center bg-secondary badge" asp-action="Payment" asp-controller="Payment">@Title</a>
                    </span>
                }
            }
            
            if (User.IsInRole("Admin"))
            {
                <span class="h5 ms-2">
                    @if (chapter.Order == 1)
                    {
                        <a class="text-decoration-none text-xxl-center bg-primary badge disabled btn" role="button" onclick="UpChapter(@chapter.ID)">
                            <i class="fa-solid fa-caret-up fa-2xl"></i>
                        </a>
                    }
                    else{
                    <a class="text-decoration-none text-xxl-center bg-primary badge btn" role="button" onclick="UpChapter(@chapter.ID)">
                        <i class="fa-solid fa-caret-up fa-2xl"></i>
                    </a>
                    }
                </span>
                <span class="h5 ms-2">
                    <a class="text-decoration-none text-xxl-center bg-primary badge" data-bs-toggle="modal" data-bs-target="#editChapterModal" role="button" onclick="EditChapter(@chapter.ID)">Edit</a>
                </span>
                <span class="h5 ms-2">
                    @if(chapter.Order == Model.Count)
                    {
                        <a class="text-decoration-none text-xxl-center bg-primary badge disabled btn" role="button" onclick="DownChapter(@chapter.ID)">
                            <i class="fa-solid fa-caret-down fa-2xl"></i>
                        </a>
                    }
                    else
                    {
                        <a class="text-decoration-none text-xxl-center bg-primary badge btn" role="button" onclick="DownChapter(@chapter.ID)">
                            <i class="fa-solid fa-caret-down fa-2xl"></i>
                        </a>
                    }
                </span>
                <span class="h5 ms-2">
                    <a class="text-decoration-none text-xxl-center bg-danger badge" role="button" onclick="DeleteChapter(@chapter.ID)">Delete</a>
                </span>
            }
        }
    </div>
}

Views/Chapter/Edit.cshtml
@model Chapter
@{
    Layout = null;
}


@using (Html.BeginForm())
{
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group row g-0 mb-3">
            @Html.LabelFor(m => m.ID, "ID", new { @class = "form-label" })
            <div class="col-md-8 offset-2">
                @Html.EditorFor(m => m.ID, new { htmlAttributes = new { @class = "form-control disabled", @Value = @Model.ID }})
            </div>
        </div>

        <div class="form-group row g-0 mb-3">
            @Html.LabelFor(m => m.Title, "Title", new { @class = "form-label" })
            <div class="col-md-8 offset-2">
                @Html.EditorFor(m => m.Title, new { htmlAttributes = new { @class = "form-control", @Value = @Model.Title }})
                @Html.ValidationMessageFor(m => m.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group row g-0 mb-3">
            @Html.LabelFor(m => m.Content, "Content", new { @class = "form-label" })
            <div class="col-md-8 offset-2">
                @Html.TextAreaFor(m => m.Content, new { htmlAttributes = new { @class = "form-control", @Value = @Model.Content }})
                @Html.ValidationMessageFor(m => m.Content, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
}

Views/Chapter/Index.cshtml
@model WebApplication1.Models.Entities.Chapter

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section NavBar{
    <partial name="_NavBarPV" />
}

<div class="p-xxl-5 ms-xxl-5 me-xxl-5" id="chapter" data="@Model.ID">

    <div class="text-center ps-xxl-5 mb-4 pe-xxl-5 ms-xxl-5 me-xxl-5">
        @{ string bookTitle = ViewBag.BookTitle; }
        @Html.ActionLink(bookTitle  ,"Index" , "Book" ,new{Id = ViewBag.BookId},new{@class="text-center text-decoration-none display-1 text-dark"})
    </div>

    <div class="align-content-sm-center mb-2 justify-content-center flex-row d-flex ps-xxl-5 pe-xxl-5 ms-xxl-5 me-xxl-5">
        @if(ViewBag.Prev != 0)
        {
            @Html.ActionLink( "previous" ,"Index" , "Chapter" ,new{id = @ViewBag.Prev},new{@class="btn btn-primary d-inline-flex"})
        }
        else
        {
            @Html.ActionLink( "previous" ,"Index" , "Chapter" ,new{id = @ViewBag.Prev},new{@class="btn btn-primary d-inline-flex disabled"})
        }
        <span class="ps-2 pe-2 h4">Chapter @Model.Order: @Model.Title</span>
        @if (ViewBag.Next != 0)
        {
            @Html.ActionLink( "Next" ,"Index" , "Chapter" ,new{id = @ViewBag.Next},new{@class="btn btn-primary d-inline-flex"})
        }
        else
        {
            @Html.ActionLink( "Next" ,"Index" , "Chapter" ,new{id = @ViewBag.Next},new{@class="btn btn-primary d-inline-flex disabled"})
        }
    </div>

    <br />

    <div class="align-content-sm-center mb-2 justify-content-center flex-row d-flex ps-xxl-5 pe-xxl-5 ms-xxl-5 me-xxl-5">
        <div class="d-inline-block ps-2">
            <select class="btn btn-secondary dropdown-toggle" name="voice" id="voice">
                <option class="dropdown-item" selected value="UK English Male">UK Male</option>
                <option class="dropdown-item" value="UK English Female">UK Female</option>
                <option class="dropdown-item" value="US English Male">US Male</option>
                <option class="dropdown-item" value="US English Female">US Female</option>
            </select>
        </div>
        <div class="d-inline-flex align-items-center ps-2" role="button" onclick="Play()">
            <i id="play" class="fa-regular fa-circle-play fa-xl"></i>
        </div>
    </div>
    <br />

    <div class="align-content-sm-center justify-content-center flex-row d-flex ps-xxl-5 pe-xxl-5 ms-xxl-5 me-xxl-5">
        @{
            List<string> chapter = Model.Content.Split('.').ToList();
            foreach (var sentence in chapter.ToList())
            {
                if (String.IsNullOrWhiteSpace(sentence))
                {
                    chapter.Remove(sentence);
                }
            }
        }
        <style type="text/css">
            .sentence {
                background-color: inherit;
            }
            .sentence:hover {
                background-color: #c0bfd6;
            }
        </style>
        <pre class="w-auto overflow-visible lead fs-5">@foreach (var (sentence,index) in chapter.Select((v,i)=>(v,i)))
            {<span class="sentence" id="sentence @index" data="@sentence" role="button" onclick="Speak(@index)">@sentence.</span>}</pre>
    </div>

    <br />

    <div class="align-content-sm-center mt-2 justify-content-center flex-row d-flex ps-xxl-5 pe-xxl-5 ms-xxl-5 me-xxl-5">

        @if (ViewBag.Prev != 0)
        {
            @Html.ActionLink( "previous" ,"Index" , "Chapter" ,new{id = @ViewBag.Prev},new{@class="btn btn-primary d-inline-flex"})
        }
        else
        {
            @Html.ActionLink( "previous" ,"Index" , "Chapter" ,new{id = @ViewBag.Prev},new{@class="btn btn-primary d-inline-flex disabled"})
        }
        <span class="ps-2 pe-2 h4">Chapter @Model.Order: @Model.Title</span>
        @if (ViewBag.Next != 0)
        {
            @Html.ActionLink( "Next" ,"Index" , "Chapter" ,new{id = @ViewBag.Next},new{@class="btn btn-primary d-inline-flex"})
        }
        else
        {
            @Html.ActionLink( "Next" ,"Index" , "Chapter" ,new{id = @ViewBag.Next},new{@class="btn btn-primary d-inline-flex disabled"})
        }
    </div>

    <br />
    <hr class="text-primary rounded-3 opacity-75" />
    <br />

    <div id="Comments" class="align-content-sm-center flex-column d-flex ps-xxl-5 pe-xxl-5 ms-xxl-5 me-xxl-5"></div>

    <div id="Comment" class="align-content-sm-center flex-column d-flex ps-xxl-5 pe-xxl-5 ms-xxl-5 me-xxl-5"></div>
</div>


@section Scripts{
    <script type="text/javascript">
        function Speak(index) {
            responsiveVoice.cancel();
            $(".sentence").each((index) => { console.log($(".sentence")[index].style = "") })
            if (document.getElementById("sentence " + index)) {
                function OnStart() {
                    document.getElementById("sentence " + index).style.backgroundColor = '#c0bfd6';
                    $("#play")[0].classList.remove("fa-circle-play");
                    $("#play")[0].classList.add("fa-circle-pause");
                }
                function OnEnd() {
                    $(".sentence").each((index) => { console.log($(".sentence")[index].style = "") })
                    $("#play")[0].classList.add("fa-circle-play");
                    $("#play")[0].classList.remove("fa-circle-pause");
                    Speak(index + 1);
                }
                var voice = document.getElementById("voice").value;
                var sentence = document.getElementById("sentence " + index).getAttributeNode("data").value.replace(/(\r\n|\n|\r)/gm, "");
                responsiveVoice.speak(sentence, voice, { onstart: OnStart, onend: OnEnd });
            }
        }
        function Play() {
            if (responsiveVoice.isPlaying()) {
                responsiveVoice.pause();
                $("#play")[0].classList.add("fa-circle-play");
                $("#play")[0].classList.remove("fa-circle-pause");
            }
            else {
                responsiveVoice.resume();
                $("#play")[0].classList.remove("fa-circle-play");
                $("#play")[0].classList.add("fa-circle-pause");
                if (!responsiveVoice.isPlaying()) {
                    Speak(0);
                }
            }
        }
        function GetComments() {
            $.ajax({
                method: "GET",
                url: "/Comment/Comments/" + @Model.ID,
                contentType: "text/html",
                success: function (data) {
                    $("#Comments").html(data);
                },
                error: function (e) {
                    console.log(e);
                }
            });
        }
        function DeleteComment(commentId) {
            $.ajax({
                method: "Post",
                url: "/Comment/Delete/" + commentId,
                success: function (data) {
                    GetComments();
                },
                error: function (e) {
                    console.log(e);
                }
            });
        }
        GetComments();
        function GetComment() {
            $.ajax({
                method: "GET",
                url: "/Comment/Comment",
                contentType: "text/html",
                success: function (data) {
                    $("#Comment").html(data);
                },
                error: function (e) {
                    console.log(e);
                }
            });
            SetComment();
        }
        function SetComment() {
            setTimeout(() => {
                document.forms[0].onsubmit = function () {
                    event.preventDefault();
                    var data = {
                        "ID": 0,
                        "Text": document.getElementById("Text").value,
                        "Votes": 0,
                        "Date": 0,
                        "ChapterID": document.getElementById("chapter").getAttributeNode("data").value,
                        "UserID": document.getElementById("addComment").getAttributeNode("data").value
                    }
                    $.ajax({
                        method: "POST",
                        url: "/Comment/Comment",
                        dataType: "json",
                        data: data,
                        success: function (data) {
                            GetComments();
                        },
                        error: function (e) {
                            $("#Comment").html(e.responseText);
                            SetComment();
                        }
                    })
                }
            }, "1000");
        }
        function UpVote(commentId, vote) {
            $.ajax({
                type: 'POST',
                url: "/Comment/UpVote",
                data:
                {
                    commentId: commentId,
                    vote: vote
                },
                success: function (data) {
                    GetComments();
                },
                error: function (e) {
                    console.log(e);
                }
            });
        }
        function DownVote(commentId, vote) {
            $.ajax({
                type: 'POST',
                url: "/Comment/DownVote",
                data:
                {
                    commentId: commentId,
                    vote: vote
                },
                success: function (data) {
                    GetComments();
                },
                error: function (e) {
                    console.log(e);
                }
            });
        }
    </script>
}